"""Wikipedia links for gallery objects.

Generated by resolving each catalog designation through the MediaWiki API with
redirects followed, then verified: all 110 Messier pages belong to a Wikipedia
Messier category, and every non-Messier article intro names its designation.

Checked in deliberately so the gallery build needs no network access.

MESSIER_WIKI / OBJECT_WIKI are hand-maintained. CALDWELL_WIKI covers all 109
Caldwell objects and is generated - regenerate it (and targets/caldwell.json)
with scripts/fetch_caldwell_wikipedia_links.py.
"""
import re

# Messier number -> Wikipedia article URL
MESSIER_WIKI = {
    1: "https://en.wikipedia.org/wiki/Crab_Nebula",  # Crab Nebula
    2: "https://en.wikipedia.org/wiki/Messier_2",  # Messier 2
    3: "https://en.wikipedia.org/wiki/Messier_3",  # Messier 3
    4: "https://en.wikipedia.org/wiki/Messier_4",  # Messier 4
    5: "https://en.wikipedia.org/wiki/Messier_5",  # Messier 5
    6: "https://en.wikipedia.org/wiki/Butterfly_Cluster",  # Butterfly Cluster
    7: "https://en.wikipedia.org/wiki/Messier_7",  # Messier 7
    8: "https://en.wikipedia.org/wiki/Lagoon_Nebula",  # Lagoon Nebula
    9: "https://en.wikipedia.org/wiki/Messier_9",  # Messier 9
    10: "https://en.wikipedia.org/wiki/Messier_10",  # Messier 10
    11: "https://en.wikipedia.org/wiki/Wild_Duck_Cluster",  # Wild Duck Cluster
    12: "https://en.wikipedia.org/wiki/Messier_12",  # Messier 12
    13: "https://en.wikipedia.org/wiki/Messier_13",  # Messier 13
    14: "https://en.wikipedia.org/wiki/Messier_14",  # Messier 14
    15: "https://en.wikipedia.org/wiki/Messier_15",  # Messier 15
    16: "https://en.wikipedia.org/wiki/Eagle_Nebula",  # Eagle Nebula
    17: "https://en.wikipedia.org/wiki/Omega_Nebula",  # Omega Nebula
    18: "https://en.wikipedia.org/wiki/Messier_18",  # Messier 18
    19: "https://en.wikipedia.org/wiki/Messier_19",  # Messier 19
    20: "https://en.wikipedia.org/wiki/Trifid_Nebula",  # Trifid Nebula
    21: "https://en.wikipedia.org/wiki/Messier_21",  # Messier 21
    22: "https://en.wikipedia.org/wiki/Messier_22",  # Messier 22
    23: "https://en.wikipedia.org/wiki/Messier_23",  # Messier 23
    24: "https://en.wikipedia.org/wiki/Small_Sagittarius_Star_Cloud",  # Small Sagittarius Star Cloud
    25: "https://en.wikipedia.org/wiki/Messier_25",  # Messier 25
    26: "https://en.wikipedia.org/wiki/Messier_26",  # Messier 26
    27: "https://en.wikipedia.org/wiki/Dumbbell_Nebula",  # Dumbbell Nebula
    28: "https://en.wikipedia.org/wiki/Messier_28",  # Messier 28
    29: "https://en.wikipedia.org/wiki/Messier_29",  # Messier 29
    30: "https://en.wikipedia.org/wiki/Messier_30",  # Messier 30
    31: "https://en.wikipedia.org/wiki/Andromeda_Galaxy",  # Andromeda Galaxy
    32: "https://en.wikipedia.org/wiki/Messier_32",  # Messier 32
    33: "https://en.wikipedia.org/wiki/Triangulum_Galaxy",  # Triangulum Galaxy
    34: "https://en.wikipedia.org/wiki/Messier_34",  # Messier 34
    35: "https://en.wikipedia.org/wiki/Messier_35",  # Messier 35
    36: "https://en.wikipedia.org/wiki/Messier_36",  # Messier 36
    37: "https://en.wikipedia.org/wiki/Messier_37",  # Messier 37
    38: "https://en.wikipedia.org/wiki/Messier_38",  # Messier 38
    39: "https://en.wikipedia.org/wiki/Messier_39",  # Messier 39
    40: "https://en.wikipedia.org/wiki/Winnecke_4",  # Winnecke 4
    41: "https://en.wikipedia.org/wiki/Messier_41",  # Messier 41
    42: "https://en.wikipedia.org/wiki/Orion_Nebula",  # Orion Nebula
    43: "https://en.wikipedia.org/wiki/Messier_43",  # Messier 43
    44: "https://en.wikipedia.org/wiki/Beehive_Cluster",  # Beehive Cluster
    45: "https://en.wikipedia.org/wiki/Pleiades",  # Pleiades
    46: "https://en.wikipedia.org/wiki/Messier_46",  # Messier 46
    47: "https://en.wikipedia.org/wiki/Messier_47",  # Messier 47
    48: "https://en.wikipedia.org/wiki/Messier_48",  # Messier 48
    49: "https://en.wikipedia.org/wiki/Messier_49",  # Messier 49
    50: "https://en.wikipedia.org/wiki/Messier_50",  # Messier 50
    51: "https://en.wikipedia.org/wiki/Whirlpool_Galaxy",  # Whirlpool Galaxy
    52: "https://en.wikipedia.org/wiki/Messier_52",  # Messier 52
    53: "https://en.wikipedia.org/wiki/Messier_53",  # Messier 53
    54: "https://en.wikipedia.org/wiki/Messier_54",  # Messier 54
    55: "https://en.wikipedia.org/wiki/Messier_55",  # Messier 55
    56: "https://en.wikipedia.org/wiki/Messier_56",  # Messier 56
    57: "https://en.wikipedia.org/wiki/Ring_Nebula",  # Ring Nebula
    58: "https://en.wikipedia.org/wiki/Messier_58",  # Messier 58
    59: "https://en.wikipedia.org/wiki/Messier_59",  # Messier 59
    60: "https://en.wikipedia.org/wiki/Messier_60",  # Messier 60
    61: "https://en.wikipedia.org/wiki/Messier_61",  # Messier 61
    62: "https://en.wikipedia.org/wiki/Messier_62",  # Messier 62
    63: "https://en.wikipedia.org/wiki/Messier_63",  # Messier 63
    64: "https://en.wikipedia.org/wiki/Black_Eye_Galaxy",  # Black Eye Galaxy
    65: "https://en.wikipedia.org/wiki/Messier_65",  # Messier 65
    66: "https://en.wikipedia.org/wiki/Messier_66",  # Messier 66
    67: "https://en.wikipedia.org/wiki/Messier_67",  # Messier 67
    68: "https://en.wikipedia.org/wiki/Messier_68",  # Messier 68
    69: "https://en.wikipedia.org/wiki/Messier_69",  # Messier 69
    70: "https://en.wikipedia.org/wiki/Messier_70",  # Messier 70
    71: "https://en.wikipedia.org/wiki/Messier_71",  # Messier 71
    72: "https://en.wikipedia.org/wiki/Messier_72",  # Messier 72
    73: "https://en.wikipedia.org/wiki/Messier_73",  # Messier 73
    74: "https://en.wikipedia.org/wiki/Messier_74",  # Messier 74
    75: "https://en.wikipedia.org/wiki/Messier_75",  # Messier 75
    76: "https://en.wikipedia.org/wiki/Little_Dumbbell_Nebula",  # Little Dumbbell Nebula
    77: "https://en.wikipedia.org/wiki/Messier_77",  # Messier 77
    78: "https://en.wikipedia.org/wiki/Messier_78",  # Messier 78
    79: "https://en.wikipedia.org/wiki/Messier_79",  # Messier 79
    80: "https://en.wikipedia.org/wiki/Messier_80",  # Messier 80
    81: "https://en.wikipedia.org/wiki/Messier_81",  # Messier 81
    82: "https://en.wikipedia.org/wiki/Messier_82",  # Messier 82
    83: "https://en.wikipedia.org/wiki/Messier_83",  # Messier 83
    84: "https://en.wikipedia.org/wiki/Messier_84",  # Messier 84
    85: "https://en.wikipedia.org/wiki/Messier_85",  # Messier 85
    86: "https://en.wikipedia.org/wiki/Messier_86",  # Messier 86
    87: "https://en.wikipedia.org/wiki/Messier_87",  # Messier 87
    88: "https://en.wikipedia.org/wiki/Messier_88",  # Messier 88
    89: "https://en.wikipedia.org/wiki/Messier_89",  # Messier 89
    90: "https://en.wikipedia.org/wiki/Messier_90",  # Messier 90
    91: "https://en.wikipedia.org/wiki/Messier_91",  # Messier 91
    92: "https://en.wikipedia.org/wiki/Messier_92",  # Messier 92
    93: "https://en.wikipedia.org/wiki/Messier_93",  # Messier 93
    94: "https://en.wikipedia.org/wiki/Messier_94",  # Messier 94
    95: "https://en.wikipedia.org/wiki/Messier_95",  # Messier 95
    96: "https://en.wikipedia.org/wiki/Messier_96",  # Messier 96
    97: "https://en.wikipedia.org/wiki/Owl_Nebula",  # Owl Nebula
    98: "https://en.wikipedia.org/wiki/Messier_98",  # Messier 98
    99: "https://en.wikipedia.org/wiki/Messier_99",  # Messier 99
    100: "https://en.wikipedia.org/wiki/Messier_100",  # Messier 100
    101: "https://en.wikipedia.org/wiki/Pinwheel_Galaxy",  # Pinwheel Galaxy
    102: "https://en.wikipedia.org/wiki/Messier_102",  # Messier 102
    103: "https://en.wikipedia.org/wiki/Messier_103",  # Messier 103
    104: "https://en.wikipedia.org/wiki/Sombrero_Galaxy",  # Sombrero Galaxy
    105: "https://en.wikipedia.org/wiki/Messier_105",  # Messier 105
    106: "https://en.wikipedia.org/wiki/Messier_106",  # Messier 106
    107: "https://en.wikipedia.org/wiki/Messier_107",  # Messier 107
    108: "https://en.wikipedia.org/wiki/Messier_108",  # Messier 108
    109: "https://en.wikipedia.org/wiki/Messier_109",  # Messier 109
    110: "https://en.wikipedia.org/wiki/Messier_110",  # Messier 110
}

# Non-Messier designation (as displayed) -> Wikipedia article URL
OBJECT_WIKI = {
    "C1": "https://en.wikipedia.org/wiki/NGC_188",  # NGC 188
    "C5": "https://en.wikipedia.org/wiki/IC_342",  # IC 342
    "C19": "https://en.wikipedia.org/wiki/IC_5146",  # IC 5146
    "C20": "https://en.wikipedia.org/wiki/North_America_Nebula",  # North America Nebula
    "IC 1318": "https://en.wikipedia.org/wiki/IC_1318",  # IC 1318
    "IC 1396": "https://en.wikipedia.org/wiki/IC_1396",  # IC 1396
    "IC 405": "https://en.wikipedia.org/wiki/IC_405",  # IC 405
    "NGC 1055": "https://en.wikipedia.org/wiki/NGC_1055",  # NGC 1055
    "NGC 1499": "https://en.wikipedia.org/wiki/California_Nebula",  # California Nebula
    "NGC 2238": "https://en.wikipedia.org/wiki/Rosette_Nebula",  # Rosette Nebula
    "NGC 2244": "https://en.wikipedia.org/wiki/NGC_2244",  # NGC 2244
    "NGC 281": "https://en.wikipedia.org/wiki/NGC_281",  # NGC 281
    "NGC 3628": "https://en.wikipedia.org/wiki/NGC_3628",  # NGC 3628
    "NGC 6992": "https://en.wikipedia.org/wiki/Veil_Nebula",  # Veil Nebula
    "NGC 7000": "https://en.wikipedia.org/wiki/North_America_Nebula",  # North America Nebula
    "NGC 7331": "https://en.wikipedia.org/wiki/NGC_7331",  # NGC 7331
    "NGC 869": "https://en.wikipedia.org/wiki/NGC_869",  # NGC 869
}


# --- BEGIN CALDWELL_WIKI (generated by scripts/fetch_caldwell_wikipedia_links.py) ---
# Caldwell number -> Wikipedia article URL
CALDWELL_WIKI = {
    1: "https://en.wikipedia.org/wiki/NGC_188",  # NGC 188
    2: "https://en.wikipedia.org/wiki/NGC_40",  # NGC 40
    3: "https://en.wikipedia.org/wiki/NGC_4236",  # NGC 4236
    4: "https://en.wikipedia.org/wiki/Iris_Nebula",  # Iris Nebula
    5: "https://en.wikipedia.org/wiki/IC_342",  # IC 342
    6: "https://en.wikipedia.org/wiki/Cat%27s_Eye_Nebula",  # Cat's Eye Nebula
    7: "https://en.wikipedia.org/wiki/NGC_2403",  # NGC 2403
    8: "https://en.wikipedia.org/wiki/NGC_559",  # NGC 559
    9: "https://en.wikipedia.org/wiki/Sh_2-155",  # Sh 2-155
    10: "https://en.wikipedia.org/wiki/NGC_663",  # NGC 663
    11: "https://en.wikipedia.org/wiki/Bubble_Nebula",  # Bubble Nebula
    12: "https://en.wikipedia.org/wiki/NGC_6946",  # NGC 6946
    13: "https://en.wikipedia.org/wiki/NGC_457",  # NGC 457
    14: "https://en.wikipedia.org/wiki/Double_Cluster",  # Double Cluster
    15: "https://en.wikipedia.org/wiki/NGC_6826",  # NGC 6826
    16: "https://en.wikipedia.org/wiki/NGC_7243",  # NGC 7243
    17: "https://en.wikipedia.org/wiki/NGC_147",  # NGC 147
    18: "https://en.wikipedia.org/wiki/NGC_185",  # NGC 185
    19: "https://en.wikipedia.org/wiki/IC_5146",  # IC 5146
    20: "https://en.wikipedia.org/wiki/North_America_Nebula",  # North America Nebula
    21: "https://en.wikipedia.org/wiki/NGC_4449",  # NGC 4449
    22: "https://en.wikipedia.org/wiki/NGC_7662",  # NGC 7662
    23: "https://en.wikipedia.org/wiki/NGC_891",  # NGC 891
    24: "https://en.wikipedia.org/wiki/NGC_1275",  # NGC 1275
    25: "https://en.wikipedia.org/wiki/NGC_2419",  # NGC 2419
    26: "https://en.wikipedia.org/wiki/NGC_4244",  # NGC 4244
    27: "https://en.wikipedia.org/wiki/Crescent_Nebula",  # Crescent Nebula
    28: "https://en.wikipedia.org/wiki/NGC_752",  # NGC 752
    29: "https://en.wikipedia.org/wiki/NGC_5005",  # NGC 5005
    30: "https://en.wikipedia.org/wiki/NGC_7331",  # NGC 7331
    31: "https://en.wikipedia.org/wiki/IC_405",  # IC 405
    32: "https://en.wikipedia.org/wiki/NGC_4631",  # NGC 4631
    33: "https://en.wikipedia.org/wiki/Veil_Nebula#Components",  # Veil Nebula
    34: "https://en.wikipedia.org/wiki/Veil_Nebula#Components",  # Veil Nebula
    35: "https://en.wikipedia.org/wiki/NGC_4889",  # NGC 4889
    36: "https://en.wikipedia.org/wiki/NGC_4559",  # NGC 4559
    37: "https://en.wikipedia.org/wiki/NGC_6885",  # NGC 6885
    38: "https://en.wikipedia.org/wiki/NGC_4565",  # NGC 4565
    39: "https://en.wikipedia.org/wiki/Eskimo_Nebula",  # Eskimo Nebula
    40: "https://en.wikipedia.org/wiki/NGC_3632",  # NGC 3632
    41: "https://en.wikipedia.org/wiki/Hyades_(star_cluster)",  # Hyades (star cluster)
    42: "https://en.wikipedia.org/wiki/NGC_7006",  # NGC 7006
    43: "https://en.wikipedia.org/wiki/NGC_7814",  # NGC 7814
    44: "https://en.wikipedia.org/wiki/NGC_7479",  # NGC 7479
    45: "https://en.wikipedia.org/wiki/NGC_5248",  # NGC 5248
    46: "https://en.wikipedia.org/wiki/NGC_2261",  # NGC 2261
    47: "https://en.wikipedia.org/wiki/NGC_6934",  # NGC 6934
    48: "https://en.wikipedia.org/wiki/NGC_2775",  # NGC 2775
    49: "https://en.wikipedia.org/wiki/Rosette_Nebula",  # Rosette Nebula
    50: "https://en.wikipedia.org/wiki/NGC_2244",  # NGC 2244
    51: "https://en.wikipedia.org/wiki/IC_1613",  # IC 1613
    52: "https://en.wikipedia.org/wiki/NGC_4697",  # NGC 4697
    53: "https://en.wikipedia.org/wiki/NGC_3115",  # NGC 3115
    54: "https://en.wikipedia.org/wiki/NGC_2506",  # NGC 2506
    55: "https://en.wikipedia.org/wiki/Saturn_Nebula",  # Saturn Nebula
    56: "https://en.wikipedia.org/wiki/NGC_246",  # NGC 246
    57: "https://en.wikipedia.org/wiki/NGC_6822",  # NGC 6822
    58: "https://en.wikipedia.org/wiki/NGC_2360",  # NGC 2360
    59: "https://en.wikipedia.org/wiki/NGC_3242",  # NGC 3242
    60: "https://en.wikipedia.org/wiki/Antennae_Galaxies",  # Antennae Galaxies
    61: "https://en.wikipedia.org/wiki/Antennae_Galaxies",  # Antennae Galaxies
    62: "https://en.wikipedia.org/wiki/NGC_247",  # NGC 247
    63: "https://en.wikipedia.org/wiki/Helix_Nebula",  # Helix Nebula
    64: "https://en.wikipedia.org/wiki/NGC_2362",  # NGC 2362
    65: "https://en.wikipedia.org/wiki/Sculptor_Galaxy",  # Sculptor Galaxy
    66: "https://en.wikipedia.org/wiki/NGC_5694",  # NGC 5694
    67: "https://en.wikipedia.org/wiki/NGC_1097",  # NGC 1097
    68: "https://en.wikipedia.org/wiki/NGC_6729",  # NGC 6729
    69: "https://en.wikipedia.org/wiki/NGC_6302",  # NGC 6302
    70: "https://en.wikipedia.org/wiki/NGC_300",  # NGC 300
    71: "https://en.wikipedia.org/wiki/NGC_2477",  # NGC 2477
    72: "https://en.wikipedia.org/wiki/NGC_55",  # NGC 55
    73: "https://en.wikipedia.org/wiki/NGC_1851",  # NGC 1851
    74: "https://en.wikipedia.org/wiki/NGC_3132",  # NGC 3132
    75: "https://en.wikipedia.org/wiki/NGC_6124",  # NGC 6124
    76: "https://en.wikipedia.org/wiki/NGC_6231",  # NGC 6231
    77: "https://en.wikipedia.org/wiki/Centaurus_A",  # Centaurus A
    78: "https://en.wikipedia.org/wiki/NGC_6541",  # NGC 6541
    79: "https://en.wikipedia.org/wiki/NGC_3201",  # NGC 3201
    80: "https://en.wikipedia.org/wiki/Omega_Centauri",  # Omega Centauri
    81: "https://en.wikipedia.org/wiki/NGC_6352",  # NGC 6352
    82: "https://en.wikipedia.org/wiki/NGC_6193",  # NGC 6193
    83: "https://en.wikipedia.org/wiki/NGC_4945",  # NGC 4945
    84: "https://en.wikipedia.org/wiki/NGC_5286",  # NGC 5286
    85: "https://en.wikipedia.org/wiki/IC_2391",  # IC 2391
    86: "https://en.wikipedia.org/wiki/NGC_6397",  # NGC 6397
    87: "https://en.wikipedia.org/wiki/NGC_1261",  # NGC 1261
    88: "https://en.wikipedia.org/wiki/NGC_5823",  # NGC 5823
    89: "https://en.wikipedia.org/wiki/NGC_6087",  # NGC 6087
    90: "https://en.wikipedia.org/wiki/NGC_2867",  # NGC 2867
    91: "https://en.wikipedia.org/wiki/NGC_3532",  # NGC 3532
    92: "https://en.wikipedia.org/wiki/Carina_Nebula",  # Carina Nebula
    93: "https://en.wikipedia.org/wiki/NGC_6752",  # NGC 6752
    94: "https://en.wikipedia.org/wiki/Jewel_Box_(star_cluster)",  # Jewel Box (star cluster)
    95: "https://en.wikipedia.org/wiki/NGC_6025",  # NGC 6025
    96: "https://en.wikipedia.org/wiki/NGC_2516",  # NGC 2516
    97: "https://en.wikipedia.org/wiki/NGC_3766",  # NGC 3766
    98: "https://en.wikipedia.org/wiki/NGC_4609",  # NGC 4609
    99: "https://en.wikipedia.org/wiki/Coalsack_Nebula",  # Coalsack Nebula
    100: "https://en.wikipedia.org/wiki/IC_2944",  # IC 2944
    101: "https://en.wikipedia.org/wiki/NGC_6744",  # NGC 6744
    102: "https://en.wikipedia.org/wiki/IC_2602",  # IC 2602
    103: "https://en.wikipedia.org/wiki/Tarantula_Nebula",  # Tarantula Nebula
    104: "https://en.wikipedia.org/wiki/NGC_362",  # NGC 362
    105: "https://en.wikipedia.org/wiki/NGC_4833",  # NGC 4833
    106: "https://en.wikipedia.org/wiki/47_Tucanae",  # 47 Tucanae
    107: "https://en.wikipedia.org/wiki/NGC_6101",  # NGC 6101
    108: "https://en.wikipedia.org/wiki/NGC_4372",  # NGC 4372
    109: "https://en.wikipedia.org/wiki/NGC_3195",  # NGC 3195
}
# --- END CALDWELL_WIKI ---


def messier_url(number):
    """Wikipedia URL for a Messier number, or None."""
    return MESSIER_WIKI.get(int(number))


def caldwell_url(number):
    """Wikipedia URL for a Caldwell number, or None."""
    return CALDWELL_WIKI.get(int(number))


def object_url(display_name):
    """Wikipedia URL for a display name such as "M31", "NGC 7331", "C20" or "C77"."""
    name = display_name.strip()
    match = re.fullmatch(r'M(\d{1,3})', name)
    if match:
        return messier_url(match.group(1))
    # Hand-maintained entries win, so curated choices are never overridden.
    if name in OBJECT_WIKI:
        return OBJECT_WIKI[name]
    match = re.fullmatch(r'C(\d{1,3})', name)
    if match:
        return caldwell_url(match.group(1))
    return None


def anchor(url, text, extra_class=''):
    """Wrap text in a Wikipedia link, or return it unchanged if we have no URL."""
    if not url:
        return text
    cls = ('wiki-link ' + extra_class).strip()
    return (f'<a class="{cls}" href="{url}" target="_blank" rel="noopener"'
            f' title="Look up {text} on Wikipedia">{text}</a>')
