"""Wikipedia links for gallery objects.

Generated by resolving each catalog designation through the MediaWiki API with
redirects followed, then verified: all 110 Messier pages belong to a Wikipedia
Messier category, and every non-Messier article intro names its designation.

Checked in deliberately so the gallery build needs no network access.
Regenerate with tools/fetch_wikipedia_links.py when targets are added.
"""
import re

# Messier number -> Wikipedia article URL
MESSIER_WIKI = {
    1: "https://en.wikipedia.org/wiki/Crab_Nebula",  # Crab Nebula
    2: "https://en.wikipedia.org/wiki/Messier_2",  # Messier 2
    3: "https://en.wikipedia.org/wiki/Messier_3",  # Messier 3
    4: "https://en.wikipedia.org/wiki/Messier_4",  # Messier 4
    5: "https://en.wikipedia.org/wiki/Messier_5",  # Messier 5
    6: "https://en.wikipedia.org/wiki/Butterfly_Cluster",  # Butterfly Cluster
    7: "https://en.wikipedia.org/wiki/Messier_7",  # Messier 7
    8: "https://en.wikipedia.org/wiki/Lagoon_Nebula",  # Lagoon Nebula
    9: "https://en.wikipedia.org/wiki/Messier_9",  # Messier 9
    10: "https://en.wikipedia.org/wiki/Messier_10",  # Messier 10
    11: "https://en.wikipedia.org/wiki/Wild_Duck_Cluster",  # Wild Duck Cluster
    12: "https://en.wikipedia.org/wiki/Messier_12",  # Messier 12
    13: "https://en.wikipedia.org/wiki/Messier_13",  # Messier 13
    14: "https://en.wikipedia.org/wiki/Messier_14",  # Messier 14
    15: "https://en.wikipedia.org/wiki/Messier_15",  # Messier 15
    16: "https://en.wikipedia.org/wiki/Eagle_Nebula",  # Eagle Nebula
    17: "https://en.wikipedia.org/wiki/Omega_Nebula",  # Omega Nebula
    18: "https://en.wikipedia.org/wiki/Messier_18",  # Messier 18
    19: "https://en.wikipedia.org/wiki/Messier_19",  # Messier 19
    20: "https://en.wikipedia.org/wiki/Trifid_Nebula",  # Trifid Nebula
    21: "https://en.wikipedia.org/wiki/Messier_21",  # Messier 21
    22: "https://en.wikipedia.org/wiki/Messier_22",  # Messier 22
    23: "https://en.wikipedia.org/wiki/Messier_23",  # Messier 23
    24: "https://en.wikipedia.org/wiki/Small_Sagittarius_Star_Cloud",  # Small Sagittarius Star Cloud
    25: "https://en.wikipedia.org/wiki/Messier_25",  # Messier 25
    26: "https://en.wikipedia.org/wiki/Messier_26",  # Messier 26
    27: "https://en.wikipedia.org/wiki/Dumbbell_Nebula",  # Dumbbell Nebula
    28: "https://en.wikipedia.org/wiki/Messier_28",  # Messier 28
    29: "https://en.wikipedia.org/wiki/Messier_29",  # Messier 29
    30: "https://en.wikipedia.org/wiki/Messier_30",  # Messier 30
    31: "https://en.wikipedia.org/wiki/Andromeda_Galaxy",  # Andromeda Galaxy
    32: "https://en.wikipedia.org/wiki/Messier_32",  # Messier 32
    33: "https://en.wikipedia.org/wiki/Triangulum_Galaxy",  # Triangulum Galaxy
    34: "https://en.wikipedia.org/wiki/Messier_34",  # Messier 34
    35: "https://en.wikipedia.org/wiki/Messier_35",  # Messier 35
    36: "https://en.wikipedia.org/wiki/Messier_36",  # Messier 36
    37: "https://en.wikipedia.org/wiki/Messier_37",  # Messier 37
    38: "https://en.wikipedia.org/wiki/Messier_38",  # Messier 38
    39: "https://en.wikipedia.org/wiki/Messier_39",  # Messier 39
    40: "https://en.wikipedia.org/wiki/Winnecke_4",  # Winnecke 4
    41: "https://en.wikipedia.org/wiki/Messier_41",  # Messier 41
    42: "https://en.wikipedia.org/wiki/Orion_Nebula",  # Orion Nebula
    43: "https://en.wikipedia.org/wiki/Messier_43",  # Messier 43
    44: "https://en.wikipedia.org/wiki/Beehive_Cluster",  # Beehive Cluster
    45: "https://en.wikipedia.org/wiki/Pleiades",  # Pleiades
    46: "https://en.wikipedia.org/wiki/Messier_46",  # Messier 46
    47: "https://en.wikipedia.org/wiki/Messier_47",  # Messier 47
    48: "https://en.wikipedia.org/wiki/Messier_48",  # Messier 48
    49: "https://en.wikipedia.org/wiki/Messier_49",  # Messier 49
    50: "https://en.wikipedia.org/wiki/Messier_50",  # Messier 50
    51: "https://en.wikipedia.org/wiki/Whirlpool_Galaxy",  # Whirlpool Galaxy
    52: "https://en.wikipedia.org/wiki/Messier_52",  # Messier 52
    53: "https://en.wikipedia.org/wiki/Messier_53",  # Messier 53
    54: "https://en.wikipedia.org/wiki/Messier_54",  # Messier 54
    55: "https://en.wikipedia.org/wiki/Messier_55",  # Messier 55
    56: "https://en.wikipedia.org/wiki/Messier_56",  # Messier 56
    57: "https://en.wikipedia.org/wiki/Ring_Nebula",  # Ring Nebula
    58: "https://en.wikipedia.org/wiki/Messier_58",  # Messier 58
    59: "https://en.wikipedia.org/wiki/Messier_59",  # Messier 59
    60: "https://en.wikipedia.org/wiki/Messier_60",  # Messier 60
    61: "https://en.wikipedia.org/wiki/Messier_61",  # Messier 61
    62: "https://en.wikipedia.org/wiki/Messier_62",  # Messier 62
    63: "https://en.wikipedia.org/wiki/Messier_63",  # Messier 63
    64: "https://en.wikipedia.org/wiki/Black_Eye_Galaxy",  # Black Eye Galaxy
    65: "https://en.wikipedia.org/wiki/Messier_65",  # Messier 65
    66: "https://en.wikipedia.org/wiki/Messier_66",  # Messier 66
    67: "https://en.wikipedia.org/wiki/Messier_67",  # Messier 67
    68: "https://en.wikipedia.org/wiki/Messier_68",  # Messier 68
    69: "https://en.wikipedia.org/wiki/Messier_69",  # Messier 69
    70: "https://en.wikipedia.org/wiki/Messier_70",  # Messier 70
    71: "https://en.wikipedia.org/wiki/Messier_71",  # Messier 71
    72: "https://en.wikipedia.org/wiki/Messier_72",  # Messier 72
    73: "https://en.wikipedia.org/wiki/Messier_73",  # Messier 73
    74: "https://en.wikipedia.org/wiki/Messier_74",  # Messier 74
    75: "https://en.wikipedia.org/wiki/Messier_75",  # Messier 75
    76: "https://en.wikipedia.org/wiki/Little_Dumbbell_Nebula",  # Little Dumbbell Nebula
    77: "https://en.wikipedia.org/wiki/Messier_77",  # Messier 77
    78: "https://en.wikipedia.org/wiki/Messier_78",  # Messier 78
    79: "https://en.wikipedia.org/wiki/Messier_79",  # Messier 79
    80: "https://en.wikipedia.org/wiki/Messier_80",  # Messier 80
    81: "https://en.wikipedia.org/wiki/Messier_81",  # Messier 81
    82: "https://en.wikipedia.org/wiki/Messier_82",  # Messier 82
    83: "https://en.wikipedia.org/wiki/Messier_83",  # Messier 83
    84: "https://en.wikipedia.org/wiki/Messier_84",  # Messier 84
    85: "https://en.wikipedia.org/wiki/Messier_85",  # Messier 85
    86: "https://en.wikipedia.org/wiki/Messier_86",  # Messier 86
    87: "https://en.wikipedia.org/wiki/Messier_87",  # Messier 87
    88: "https://en.wikipedia.org/wiki/Messier_88",  # Messier 88
    89: "https://en.wikipedia.org/wiki/Messier_89",  # Messier 89
    90: "https://en.wikipedia.org/wiki/Messier_90",  # Messier 90
    91: "https://en.wikipedia.org/wiki/Messier_91",  # Messier 91
    92: "https://en.wikipedia.org/wiki/Messier_92",  # Messier 92
    93: "https://en.wikipedia.org/wiki/Messier_93",  # Messier 93
    94: "https://en.wikipedia.org/wiki/Messier_94",  # Messier 94
    95: "https://en.wikipedia.org/wiki/Messier_95",  # Messier 95
    96: "https://en.wikipedia.org/wiki/Messier_96",  # Messier 96
    97: "https://en.wikipedia.org/wiki/Owl_Nebula",  # Owl Nebula
    98: "https://en.wikipedia.org/wiki/Messier_98",  # Messier 98
    99: "https://en.wikipedia.org/wiki/Messier_99",  # Messier 99
    100: "https://en.wikipedia.org/wiki/Messier_100",  # Messier 100
    101: "https://en.wikipedia.org/wiki/Pinwheel_Galaxy",  # Pinwheel Galaxy
    102: "https://en.wikipedia.org/wiki/Messier_102",  # Messier 102
    103: "https://en.wikipedia.org/wiki/Messier_103",  # Messier 103
    104: "https://en.wikipedia.org/wiki/Sombrero_Galaxy",  # Sombrero Galaxy
    105: "https://en.wikipedia.org/wiki/Messier_105",  # Messier 105
    106: "https://en.wikipedia.org/wiki/Messier_106",  # Messier 106
    107: "https://en.wikipedia.org/wiki/Messier_107",  # Messier 107
    108: "https://en.wikipedia.org/wiki/Messier_108",  # Messier 108
    109: "https://en.wikipedia.org/wiki/Messier_109",  # Messier 109
    110: "https://en.wikipedia.org/wiki/Messier_110",  # Messier 110
}

# Non-Messier designation (as displayed) -> Wikipedia article URL
OBJECT_WIKI = {
    "C1": "https://en.wikipedia.org/wiki/NGC_188",  # NGC 188
    "C5": "https://en.wikipedia.org/wiki/IC_342",  # IC 342
    "C19": "https://en.wikipedia.org/wiki/IC_5146",  # IC 5146
    "C20": "https://en.wikipedia.org/wiki/North_America_Nebula",  # North America Nebula
    "IC 1318": "https://en.wikipedia.org/wiki/IC_1318",  # IC 1318
    "IC 1396": "https://en.wikipedia.org/wiki/IC_1396",  # IC 1396
    "IC 405": "https://en.wikipedia.org/wiki/IC_405",  # IC 405
    "NGC 1055": "https://en.wikipedia.org/wiki/NGC_1055",  # NGC 1055
    "NGC 1499": "https://en.wikipedia.org/wiki/California_Nebula",  # California Nebula
    "NGC 2238": "https://en.wikipedia.org/wiki/Rosette_Nebula",  # Rosette Nebula
    "NGC 2244": "https://en.wikipedia.org/wiki/NGC_2244",  # NGC 2244
    "NGC 281": "https://en.wikipedia.org/wiki/NGC_281",  # NGC 281
    "NGC 3628": "https://en.wikipedia.org/wiki/NGC_3628",  # NGC 3628
    "NGC 6992": "https://en.wikipedia.org/wiki/Veil_Nebula",  # Veil Nebula
    "NGC 7000": "https://en.wikipedia.org/wiki/North_America_Nebula",  # North America Nebula
    "NGC 7331": "https://en.wikipedia.org/wiki/NGC_7331",  # NGC 7331
    "NGC 869": "https://en.wikipedia.org/wiki/NGC_869",  # NGC 869
}


def messier_url(number):
    """Wikipedia URL for a Messier number, or None."""
    return MESSIER_WIKI.get(int(number))


def object_url(display_name):
    """Wikipedia URL for a display name such as "M31", "NGC 7331" or "C20"."""
    match = re.fullmatch(r'M(\d{1,3})', display_name.strip())
    if match:
        return messier_url(match.group(1))
    return OBJECT_WIKI.get(display_name.strip())


def anchor(url, text, extra_class=''):
    """Wrap text in a Wikipedia link, or return it unchanged if we have no URL."""
    if not url:
        return text
    cls = ('wiki-link ' + extra_class).strip()
    return (f'<a class="{cls}" href="{url}" target="_blank" rel="noopener"'
            f' title="Look up {text} on Wikipedia">{text}</a>')
