#!/usr/bin/env python3
"""Resolve a Wikipedia article for each of the 109 Caldwell objects.

Candidate article titles are taken from the links in the Wikipedia Caldwell table
(common-name column first, then the NGC/IC designation column), resolved through the
MediaWiki API with redirects followed, then verified: the article must actually name
one of the object's designations or its common name. The intro is checked first; a
candidate the intro does not confirm is retried against the article's full text.

Writes:
  targets/caldwell.json          - adds "wikipedia_url" to each object
  gallery/wikipedia_links.py     - regenerates the CALDWELL_WIKI block between markers

so the gallery build itself needs no network access.

    python3 scripts/fetch_caldwell_wikipedia_links.py
"""
import json
import re
import sys
import time
import urllib.parse
import urllib.request
import os
from pathlib import Path


def _find_astro_root():
    """Walk up from this file to the directory holding sessions/ and targets/.

    Works whether the script runs from ~/astro/scripts (a symlink) or from its
    real home in the gallery repo's tools/ folder. ASTRO_DIR env var overrides.
    """
    env = os.environ.get("ASTRO_DIR")
    if env:
        return Path(env)
    for p in Path(__file__).resolve().parents:
        if (p / "sessions").is_dir() and (p / "targets").is_dir():
            return p
    return Path.home() / "astro"

ROOT = _find_astro_root()
sys.path.insert(0, str(ROOT / "scripts"))
from build_caldwell_mapping import WIKI, fetch, ATTR_RE  # noqa: E402

API = "https://en.wikipedia.org/w/api.php"
UA = {"User-Agent": "astro-catalog-build/1.0 (personal astrophotography catalog)"}
CATALOG = ROOT / "targets" / "caldwell.json"
LINKS = ROOT / "gallery" / "wikipedia_links.py"
BEGIN = "# --- BEGIN CALDWELL_WIKI (generated by scripts/fetch_caldwell_wikipedia_links.py) ---"
END = "# --- END CALDWELL_WIKI ---"


def api(**params):
    q = urllib.parse.urlencode(dict(action="query", format="json", **params))
    req = urllib.request.Request(f"{API}?{q}", headers=UA)
    return json.load(urllib.request.urlopen(req, timeout=60))


def link_targets(cell):
    """Wikipedia link targets inside one wikitext cell, in order."""
    cell = re.sub(r"<ref.*?</ref>", "", cell, flags=re.DOTALL)
    cell = re.sub(r"<ref[^>]*/>", "", cell)
    out = []
    for m in re.finditer(r"\[\[([^\]\|]+)(?:\|[^\]]+)?\]\]", cell):
        t = m.group(1).strip()
        if not t.lower().startswith(("file:", "image:")):
            out.append(t)
    return out


def candidates(wikitext):
    """Caldwell number -> ordered candidate article titles."""
    lines = wikitext.splitlines()
    start = next(i for i, l in enumerate(lines) if l.startswith('{| class="wikitable sortable"'))
    end = next(i for i in range(start, len(lines)) if lines[i].strip() == "|}")
    rows, cur = [], None
    for line in lines[start + 1:end]:
        if line.startswith("|-"):
            if cur:
                rows.append(cur)
            cur = []
        elif cur is not None:
            cur.append(line)
    if cur:
        rows.append(cur)

    out = {}
    for row in rows:
        cells = []
        for line in row:
            if line.startswith("|") and not line.startswith("|-"):
                cells.append(line[1:])
            elif cells:
                cells[-1] += " " + line
        if len(cells) < 8:
            continue
        m = re.match(r"C(\d+)$", re.sub(r"\{\{hs\|\d+\}\}", "", cells[0]).strip())
        if m:
            out[int(m.group(1))] = link_targets(cells[2]) + link_targets(cells[1])
    return out


def resolve(titles, intro_only=True):
    """Requested title -> {title, url, text}, redirects followed. Missing pages omitted."""
    found = {}
    titles = sorted(titles)
    for i in range(0, len(titles), 20):
        batch = titles[i:i + 20]
        extra = {"exintro": "1"} if intro_only else {}
        data = api(redirects="1", titles="|".join(batch), prop="info|extracts",
                   inprop="url", explaintext="1", exlimit="20", **extra)
        query = data["query"]
        alias = {n["from"]: n["to"] for n in query.get("normalized", [])}
        alias.update({r["from"]: r["to"] for r in query.get("redirects", [])})
        pages = {p["title"]: p for p in query["pages"].values()}
        for t in batch:
            final = t
            for _ in range(5):
                final = alias.get(final, final)
            page = pages.get(final)
            if page and "missing" not in page:
                found[t] = {"title": page["title"], "url": page["fullurl"],
                            "text": page.get("extract") or ""}
        time.sleep(0.2)
    return found


def names_object(entry, info):
    """Does this article actually name the object?"""
    haystack = (info["title"] + " " + info["text"]).lower()
    desigs = entry["ngc"] + entry["ic"] + entry["other_designations"] + entry["also_designated"]
    needles = [d.lower() for d in desigs] + [d.replace(" ", "").lower() for d in desigs]
    if entry["common_name"]:
        needles += [p.strip().lower() for p in entry["common_name"].split(",")]
    needles.append(f"caldwell {entry['number']}")
    return any(n and n in haystack for n in needles)


def main():
    doc = json.loads(CATALOG.read_text())
    entries = {e["number"]: e for e in doc["objects"]}

    cands = candidates(fetch(WIKI).decode("utf-8"))
    if sorted(cands) != list(range(1, 110)):
        sys.exit(f"expected C1-C109 candidates, got {len(cands)}")

    wanted = {t.split("#")[0] for cs in cands.values() for t in cs}
    print(f"resolving {len(wanted)} distinct article titles...")
    pages = resolve(wanted)
    if len(pages) != len(wanted):
        print(f"  note: {len(wanted) - len(pages)} title(s) did not resolve: "
              f"{sorted(wanted - set(pages))}")

    picks, retry = {}, set()
    for n in range(1, 110):
        for t in cands[n]:
            base = t.split("#")[0]
            if base in pages and names_object(entries[n], pages[base]):
                picks[n] = (t, pages[base])
                break
        else:
            retry.update(t.split("#")[0] for t in cands[n])

    if retry:
        # The intro alone did not confirm these; check the full article text.
        print(f"intro check inconclusive for {len(retry)} title(s), retrying on full text...")
        full = resolve(retry, intro_only=False)
        for n in range(1, 110):
            if n in picks:
                continue
            for t in cands[n]:
                base = t.split("#")[0]
                if base in full and names_object(entries[n], full[base]):
                    picks[n] = (t, {**full[base], "url": pages[base]["url"]})
                    break

    unlinked = [n for n in range(1, 110) if n not in picks]
    if unlinked:
        sys.exit(f"no verified article for: {['C%d' % n for n in unlinked]}")

    urls = {}
    for n, (requested, info) in picks.items():
        frag = requested.split("#")[1] if "#" in requested else None
        urls[n] = (info["url"] + ("#" + frag.replace(" ", "_") if frag else ""), info["title"])

    # --- targets/caldwell.json -------------------------------------------------
    for e in doc["objects"]:
        e["wikipedia_url"] = urls[e["number"]][0]
    doc["field_notes"]["wikipedia_url"] = (
        "Article resolved via the MediaWiki API and verified to name the object; "
        "generated by scripts/fetch_caldwell_wikipedia_links.py.")
    CATALOG.write_text(json.dumps(doc, indent=2, ensure_ascii=False) + "\n")

    # --- gallery/wikipedia_links.py --------------------------------------------
    block = [BEGIN, "# Caldwell number -> Wikipedia article URL", "CALDWELL_WIKI = {"]
    for n in range(1, 110):
        url, title = urls[n]
        block.append(f'    {n}: "{url}",  # {title}')
    block += ["}", END]

    src = LINKS.read_text()
    generated = "\n".join(block)
    if BEGIN in src:
        src = re.sub(re.escape(BEGIN) + r".*?" + re.escape(END), generated, src, flags=re.DOTALL)
    else:
        anchor_point = "\n\ndef messier_url("
        if anchor_point not in src:
            sys.exit("could not find insertion point in gallery/wikipedia_links.py")
        src = src.replace(anchor_point, "\n\n" + generated + "\n" + anchor_point, 1)
    LINKS.write_text(src)

    print(f"ok: {len(urls)} Caldwell links verified")
    print(f"  {CATALOG}")
    print(f"  {LINKS}")


if __name__ == "__main__":
    main()
